"""added seeds

Revision ID: 4be1d3dc61ac
Revises: 
Create Date: 2023-08-15 13:07:44.508425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be1d3dc61ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('band_name', sa.String(), nullable=True),
    sa.Column('opener', sa.String(), nullable=True),
    sa.Column('concert_image', sa.String(), nullable=True),
    sa.Column('setlist_link', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_concerts_user_id_users')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_concerts_venue_id_venues')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('festivals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('festival_name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('festival_image', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_festivals_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('festival_bands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('festival_id', sa.Integer(), nullable=True),
    sa.Column('band_name', sa.String(), nullable=True),
    sa.Column('band_image', sa.String(), nullable=True),
    sa.Column('setlist_link', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('headliner', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], name=op.f('fk_festival_bands_festival_id_festivals')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('festival_bands')
    op.drop_table('festivals')
    op.drop_table('concerts')
    op.drop_table('venues')
    op.drop_table('users')
    # ### end Alembic commands ###
